#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the 4-to_infinity_and_beyond process
PID=$(pgrep 4-to_infinity_and_beyond)

# If the process is running, kill it
if [ -n "$PID" ]; then
    kill "$PID"
fi
