#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file with specific information

while IFS=: read -r username _ userid _ homedir _; do
    echo "$username:$userid:$homedir"
done < /etc/passwd
