#!/usr/bin/env bash
# This script configures SSH to use a specific private key when connecting to a server

# Generate RSA key pair with specific name and passphrase
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N 'betty'

# Append or create SSH configuration file
touch ~/.ssh/config

# Add entry to SSH configuration file specifying private key
echo -e "Host *\n  IdentityFile ~/.ssh/school" >> ~/.ssh/config
